package com.sip.flymobile.data.table;

import com.j256.ormlite.field.DatabaseField;

public class ContactList {
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	public int id;
	@DatabaseField
	public String username;
	@DatabaseField
	public String name;	
	@DatabaseField
	public String nickname;
	@DatabaseField
	public String email;
	@DatabaseField
	public String avastar;
	@DatabaseField
	public String favorite;
	@DatabaseField
	public int group_type;
	@DatabaseField
	public String creator;
	@DatabaseField
	public String domain;
	@DatabaseField
	public String address;
	@DatabaseField
	public String postal;	
	@DatabaseField
	public String company;	
}
